/** Auto-generated by scripts/optimize-partner-logos.mjs — do not edit manually. */
export const PARTNER_LOGOS_MANIFEST = [
  { src: '/partner-logo-optimized/partner-logo-1.webp', alt: 'Partner company logo 1' },
  { src: '/partner-logo-optimized/partner-logo-2.webp', alt: 'Partner company logo 2' },
  { src: '/partner-logo-optimized/partner-logo-3.webp', alt: 'Partner company logo 3' },
  { src: '/partner-logo-optimized/partner-logo-4.webp', alt: 'Partner company logo 4' },
  { src: '/partner-logo-optimized/partner-logo-5.webp', alt: 'Partner company logo 5' },
  { src: '/partner-logo-optimized/partner-logo-6.webp', alt: 'Partner company logo 6' },
  { src: '/partner-logo-optimized/partner-logo-7.webp', alt: 'Partner company logo 7' },
  { src: '/partner-logo-optimized/partner-logo-8.webp', alt: 'Partner company logo 8' },
  { src: '/partner-logo-optimized/partner-logo-9.webp', alt: 'Partner company logo 9' },
  { src: '/partner-logo-optimized/partner-logo-10.webp', alt: 'Partner company logo 10' },
  { src: '/partner-logo-optimized/partner-logo-11.webp', alt: 'Partner company logo 11' },
  { src: '/partner-logo-optimized/partner-logo-12.webp', alt: 'Partner company logo 12' },
  { src: '/partner-logo-optimized/partner-logo-13.webp', alt: 'Partner company logo 13' },
  { src: '/partner-logo-optimized/adams-logo.webp', alt: 'Adams Logo' },
  { src: '/partner-logo-optimized/alicia-logo.webp', alt: 'Alicia Logo' },
  { src: '/partner-logo-optimized/cecil-logo.webp', alt: 'Cecil Logo' },
  { src: '/partner-logo-optimized/cv-logo.webp', alt: 'Cv Logo' },
  { src: '/partner-logo-optimized/deb-logo.webp', alt: 'Deb Logo' },
  { src: '/partner-logo-optimized/lewis-logo-animated.mp4', alt: 'Lewis Logo Animated logo', kind: 'video' },
  { src: '/partner-logo-optimized/o-m-logo.webp', alt: 'O M Logo' },
  { src: '/partner-logo-optimized/om-logo.webp', alt: 'Om Logo' },
  { src: '/partner-logo-optimized/rango-logo-white.webp', alt: 'Rango Logo White logo' },
  { src: '/partner-logo-optimized/weston-logo-white.webp', alt: 'Weston Logo White logo' },
] as const;

export type PartnerLogoManifestEntry = (typeof PARTNER_LOGOS_MANIFEST)[number];
